#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#   Kenneth Lareau <klareau@tagged.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

path=(/usr/local/homebrew/bin /usr/local/git/bin $path)
path=($path /Library/PostgreSQL/9.5/bin /usr/local/mysql/bin $HOME/bin)

export LESS=-cieMR

# History settings
setopt NO_SHARE_HISTORY   # Not desired with all the shells I have open
setopt NO_INC_APPEND_HISTORY   # Not desired with all the shells I have open
export HISTSIZE=3000
export DIRSTACKSIZE=20

# Undo damage by annoying Linux prompt settings that create havoc
# with the titlebar
precmd () { print -Pn "\e]0;%m \a" }
preexec () { print -Pn "\e]0;%m \a" }

#PROMPT='%B[%m:%n]%b %~
#(%!%) '                  # two line prompt
#RPROMPT=' %B%W %t%b'     # prompt for right side of screen

alias nohostssh='ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no'
alias goodssl='/usr/local/opt/openssl/bin/openssl'

if (( $+commands[keychain] )); then
    eval $(keychain -q --eval --agents ssh --inherit any id_rsa)
fi

disable_anaconda () { path=(${(@)path:#$HOME/anaconda/bin}) }
enable_anaconda () { path=($HOME/anaconda/bin $path) }
ipython () { enable_anaconda && command ipython "$@" && disable_anaconda }
update_zprezto () { (cd ~/.zprezto && git pull && git submodule update --init --recursive) }

#source $HOME/repos/git/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
