#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#   Kenneth Lareau <klareau@tagged.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

path=(/usr/local/git/bin /opt/subversion/bin $path)
path=($path /usr/local/mysql/bin $HOME/bin)

export LESS=-cieMR

# History settings
export HISTSIZE=1000
export DIRSTACKSIZE=20

# Undo damage by annoying Linux prompt settings that create havoc
# with the titlebar
precmd () { print -Pn "\e]0;%m \a" }
preexec () { print -Pn "\e]0;%m \a" }

#PROMPT='%B[%m:%n]%b %~
#(%!%) '                  # two line prompt
#RPROMPT=' %B%W %t%b'     # prompt for right side of screen

alias nohostssh='ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no'
alias tag_mysql_read='mysql -h opsdb.tagged.com -u tagopsdb_reader -p TagOpsDB'
alias tag_mysql_root='mysql -h opsdb.tagged.com -u root -p TagOpsDB'
alias tag_mysql_write='mysql -h opsdb.tagged.com -u tagopsdb_writer -p TagOpsDB'

alias pm='pupmanage'
alias pmul='pupmanage update-local'
alias pmpd='pupmanage push-to-dev'
alias pmps='pupmanage push-to-stage'
alias pmpp='pupmanage push-to-prod'
alias pmpa='pupmanage push-to-all'

eval $(keychain -q --eval --agents ssh --inherit any id_rsa)

#source $HOME/repos/git/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
